aws:
  region: us-east-1
  role_name: LambdaS3AccessRole
s3:
  bucket_name: aws-lambda-pet-project-bucket
  incoming_folder: incoming
  archive_folder: archive
func:
  name: S3FileProcessor
  file_path: lambda_function.py
  pandas_layer_arn: arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python313:1
